### ISSUE TITLE
About AES encode 

### ISSUE THREAD

**Issue by szmulder** [weltkante/managed-lzma#1] opened 2015-02-22 21:21 UTC
I can see you support AesDecoderStream, do you support AesEecoderStream?
How can I user it if supported?

Thanks!

**Comment by weltkante** [comment] 2015-02-23 17:12
So far I've only ported the AES decoder so it's currently not possible to output encrypted archives, but I'll take a look. If System.Security.Cryptography outputs data compatible to the 7z format I may be able to implement it.

**Comment by szmulder** [comment] 2015-02-23 20:23
I have to say your project is the best 7Z project I have ever seen.
Very easy to use as well!

**Comment by weltkante** [comment] 2015-02-24 20:47
I've done some initial testing and it looks like it is possible to use System.Security.Cryptography for implementing an AES encoder. However before doing so I need to fix some other issues, in particular issue #5 is important to verify the password when you later unpack an encrypted 7z archive. If the (optional) hash is not present 7z can still decrypt the file but cannot tell if your password was correct. If it isn't correct you get random garbage in the decrypted file, but 7z doesn't realize that when it doesn't have a checksum to compare with.

**Comment by szmulder** [comment] 2015-02-24 22:13
Very nice work!

**Comment by szmulder** [comment] 2015-03-03 00:14
Is the AES encoder available to use?

**Comment by weltkante** [comment] 2015-03-03 10:16
Sorry, I only have limited time and have been using that to work on issue #4 - right now I can't get the sample to work as it was intended so there is not much point in working at new encoder variants until that bug is fixed.

I do have a prototype version which can be used in the `ArchiveWriter.ConnectEncoder` call but currently this means you have to chose between encryption and compression and can't use them both at the same time, which is probably not really useful, so I didn't bother to check it in.

**Comment by weltkante** [comment] 2015-03-05 20:00
After fixing the deadlock issue I'll work on AES over the next week.

**Comment by weltkante** [comment] 2015-03-12 20:37
Initial implementation for AES encryption is checked in, it should match what 7z 9.22 does.

The sandbox-7z project is updated as an example, but basically you create an EncryptionProvider with the desired password and assign it to the ArchiveWriter and the encoders will pick it up.

**Closed by weltkante** 2015-03-12 20:37 UTC
Labels: enhancement

**Comment by szmulder** [comment] 2015-03-12 21:08
Your are my hero! :)
