### ISSUE TITLE
Create a NuGet package

### ISSUE THREAD

**Issue by voltagex** [weltkante/managed-lzma#8] opened 2015-08-18 23:29 UTC
Any chance of a NuGet package for this library?

**Comment by weltkante** [comment] 2015-08-19 20:07
Are you looking for the LZMA or 7z part of the library? The 7z part is not ready for distribution, its still in experimental stages and changes a lot every time I work on it. For the LZMA encoders/decoders I could consider creating a nuget package however.

Currently I'm concentrating my work on creating a "universal windows" version of the library, which has the advantage of being able to use C++ and getting the performance of the native lzma implementation. Once that's done I should have a better idea how the API will look like and will proceed on cleaning up the managed libraries. That would be the point where I'd create nuget packages I guess. If you'd like to have a nuget package for the LZMA part sooner I could make a prerelease version sometime next week, but the API would not be final.

**Comment by sepehr1014** [comment] 2015-08-19 20:10
Wow! A complete library for .NET Core would be awesome!

**Comment by voltagex** [comment] 2015-12-11 11:59
Ping on this :+1: - MyGet may be better as it actually allows deleting packages. AppVeyor/Travis may help you automate builds so there's less work for you

**Comment by weltkante** [comment] 2015-12-11 13:44
I did a quick check on myget and I don't think I'd be immediately using any of the additional services they provide.

(Also deleting packages is a really bad idea, it makes the service unreliable and makes users want to mirror the packages in case stuff gets deleted, so as a user I'm actually glad nuget doesn't allow it!)

**Comment by weltkante** [comment] 2015-12-11 13:48
Also as a status update on the ticket, some of it mentioned on gitter:

I'm currently working on wrapping up the new API (which is already merged into the master branch) and planning beta nuget packages by the end of the month.

However I'm having some problems creating a portable library for the project in VS 2015 so it might be just desktop libraries on nuget for now. The problem is that when I define a portable library in VS 2015 and want to add the required nuget libraries for cryptography (which exist but are rather new) then VS and/or nuget errors out resolving dependencies. I hoped VS Update 1 would fix that but it didn't.

**Comment by voltagex** [comment] 2015-12-11 14:44
What's the package source? Perhaps a solution-level packages.config could help.

**Comment by voltagex** [comment] 2015-12-11 14:45
Also, can you paste some of the errors here for reference?

**Comment by weltkante** [comment] 2015-12-11 15:50
Just create a portable library project and and add a nuget reference to System.Security.Cryptography (the corefx package containing the AES encryption/decryption algorithms) and it will fail.

```
System.Security.Cryptography.Algorithms 4.0.0-beta-23516 is not compatible with .NETPlatform,Version=v5.0.
Some packages are not compatible with .NETPlatform,Version=v5.0.
All packages are compatible with .NETFramework,Version=v4.6.
All packages are compatible with UAP,Version=v10.0.
All packages are compatible with DNXCore,Version=v5.0.
All packages are compatible with .NETFramework,Version=v4.6 (win-x86).
All packages are compatible with .NETFramework,Version=v4.6 (win-x64).
All packages are compatible with UAP,Version=v10.0 (win10-x86).
All packages are compatible with UAP,Version=v10.0 (win10-x86-aot).
All packages are compatible with UAP,Version=v10.0 (win10-x64).
All packages are compatible with UAP,Version=v10.0 (win10-x64-aot).
All packages are compatible with UAP,Version=v10.0 (win10-arm).
All packages are compatible with UAP,Version=v10.0 (win10-arm-aot).
All packages are compatible with DNXCore,Version=v5.0 (win7-x86).
All packages are compatible with DNXCore,Version=v5.0 (win7-x64).
```

Note that whatever framework you chose for the portable library to support doesn't matter, it always errors out on ".NET Platform 5.0" (and the nuget package indeed says it requires ".NET Platform 5.1" - but I don't see where I can configure that in Visual Studio). So far I have not found any reference on the net what that ".NET Platform 5.0" means. There is the possibility that VS simply cannot deal with these corefx libraries yet.

I haven't done anything with .NET Core yet, so portable libraries may actually be the wrong project type. If you have any links or suggestions to share that would probably help.

**Comment by weltkante** [comment] 2015-12-11 15:57
Actually while reproducing the issue for you I noticed that if I don't take the newest version of the library there's an older one which still supported ".NET Platform 5.0" and also has AES support, so I may get away referencing that one.

**Comment by weltkante** [comment] 2015-12-22 18:41
I've been able to setup a [portable library project](https://github.com/weltkante/managed-lzma/tree/master/portable) and compile it, but nuget refuses to build a package out of it. I'm getting an error `targetFramework attribute not declared` if I run nuget on the project.

For the record, I've been trying to follow the explanations from this [blog post](http://blogs.msdn.com/b/lucian/archive/2015/09/15/writing-a-nuget-package-for-vs2015-rtm-repost.aspx)

I'd appreciate any hints, links, or a working nuspec file ;-)

For now I've made a nuget package for the desktop framework to get started. You can find it under https://www.nuget.org/packages/ManagedLzma

I don't have much of a documentation or examples yet, but you can take a look at the [code in the repository](https://github.com/weltkante/managed-lzma/blob/master/sandbox-7z/Program.cs) to get started.

Of course any testing and potential bug reports are welcome too.

**Comment by weltkante** [comment] 2016-01-04 15:31
I've checked in a [2nd variant](https://github.com/weltkante/managed-lzma/tree/master/portable-compat) of a portable project which uses older nuget references and the older `packages.config` instead of `project.json` format. Of course that means it won't target .NET Core, ASP.NET 5 or UWP (these need the project.json file which I can't get to work).

Not pushing a portable nuget package yet because I want to try to figure out if I can get the desktop and portable build into the same package (instead of making two distinct packages).

**Comment by weltkante** [comment] 2017-09-11 18:38
I've pushed a .NET Standard 1.3/2.0 nuget package under v0.2-alpha-7 which should cover most platforms which previously were using portable. If anyone still needs portable support, I have it working, I just don't know how to write a nuspec for it. Unless someone still requires portable (and knows how to write the nuspec) I'll stick to .NET Standard.

**Closed by weltkante** 2017-09-11 18:38 UTC
